server:
    port: 8881
book:
    desc: ${book.author} is writhing 《 ${book.name} 》 #UTF-8
management:
    endpoints:
        web:
            exposure:
                include: "*"
---
                exclude: "env,beans"
---
spring:
    profiles: test
server:
    port: 8882
---
spring:
    profiles: prod
server:
    port: 8883